utils::globalVariables(c("n0", "n1", "positive", "pp_threshold",
                         "ppp", "y0", "y1", "n0_null", "n1_null",
                         "positive_null", "n0_alt", "n1_alt",
                         "positive_alt",
                         "prop_pos_null", "prop_pos_alt", "prop_stopped_null",
                         "Youden's index", "mean_n1_null", "design",
                         "ppp_threshold", "mean_n1_alt", "n_dist_metric",
                         "Type I error", "Power", "Design", 
                         "Average N under the null", 
                         "Average N under the alternative",
                         "Distance to optimal efficiency",
                         "mean_n0_null", "mean_n0_alt", "mean_n_null",
                         "mean_n_alt", "ab_dist_metric", 
                         "Distance to optimal accuracy"))